### ISSUE TITLE
Ошибка. Проверьте пожалуйста wallpapers_calculation.py

### ISSUE THREAD

**Issue by ayrat-l** [ayrat-l/python-demo#1]
@coursar **Выдает ошибку** 
```
Traceback (most recent call last):
  File "C:/python-demo/wallpapers_calculation.py", line 15, in <module>
    canvas_quantity = perimeter_of_the_room / width_of_the_wallpaper #Расчет количества полотен обоев
TypeError: unsupported operand type(s) for /: 'function' and 'float'
```
**Прошу помощи , как это исправить.**

**Comment by coursar** [comment]
Читаете: строка 15, не поддерживается оператор деления для функции и float
Смотрите:
https://github.com/ayrat-l/python-demo/blob/974369c9fc453565e70673ba96c7e38e133cebdd/wallpapers_calculation.py#L15

Вы пытаетесь функцию, разделить на число, так нельзя. Можно вызвать функцию и результат, который она вернёт, разделить на число.

Должно быть:
```python
canvas_quantity = perimeter_of_the_room (x, y) / width_of_the_wallpaper
```
