### ISSUE TITLE
Отформатируйте код так, чтобы удобно было воспринимать. Используйте для этого пустые строки.

### ISSUE THREAD

**Issue by coursar** [ayrat-l/python-demo#4]
https://github.com/ayrat-l/python-demo/blob/974369c9fc453565e70673ba96c7e38e133cebdd/wallpapers_calculation.py#L4-L22

**Comment by coursar** [comment]
Не надо закрывать issue, если вы его не поправили

**Comment by ayrat-l** [comment]
Прошу прощения, я думал если один раз добавить вас в "Коллабораторы", то все мои проекты будут вам доступны.

Сейчас добавил вас на два репозитория: 

1) https://github.com/ayrat-l/distance_calculation/

2) https://github.com/ayrat-l/wallpapers-calculation/

Это домашки по расчету расстояния с остатком топлива и расчет необходимого количества рулонов обоев при ремонте.

Проект python-demo можете не смотреть. Жду ответа...

**Comment by coursar** [comment]
ок
